Nombre = "Agustin"
Apellido = "Waizman"
Edad = 24
Email = "aguswaizman98@gmail.com"
Telefono = 3624680121
Casado = False
Con_Hijos = False
Lista_de_amigos = ["Matias", "Ulises", "Miguel", "Lautaro", "Lucas"]
Peliculas_vistas = { 1: "El protegido", 2: "Fragmentado", 3: "Glass"}